### ISSUE TITLE
Test URL error

### ISSUE THREAD

**Issue by 726411951** [zuoge85/OpenMajiang#11]
the test URL [测试](http://www.paipaimj.com/)  jump to the error page

**Comment by didoupeanut** [comment]
你好请问你能告诉我怎么部署 client项目的吗?我运行的时候总是报错，
Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni64-1.8 in java.library.path, no leveldbjni-1.8 in java.library.path
at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at org.fusesource.leveldbjni.JniDBFactory.<clinit>(JniDBFactory.java:48)
	at majiang.client.db.DbManager.init(DbManager.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

这个找不到库怎么解决啊?我看了依赖文件，已经依赖了这个库了，也下载了，这个leveldb的jni就是报错，很烦哦

**Comment by 726411951** [comment]
@didoupeanut 我也没有clone下来，因为没有网页看效果
